### ISSUE TITLE
Open .dll worldedit

### ISSUE THREAD

**Issue by Xota6bi4h** [Terraria-Builders-Community/WorldEdit#2]

**Comment by csmir** [comment]
???

**Comment by Xota6bi4h** [comment]
![image](https://user-images.githubusercontent.com/97909867/230713494-0b6c14a7-fdad-4ebb-9d73-b1074a38558e.png)

**Comment by xtpkt** [comment]
Run `dotnet build` in CLI.

The readme is behind as the repository is currently open sourced. There is no release currently, that shouldn't stop anyone from compiling themselves, which is a preferable practice given the rancid nature of working with terraria.
